### ISSUE TITLE
Calling chat.push() multible times only adds the first message

### ISSUE THREAD

**Issue by simonfrey** [VaguelySerious/gram-node-frontend#1]
Calling chat.push() multible times only adds the first message

**Comment by VaguelySerious** [comment]
Addressed in [6a0a4b](https://github.com/VaguelySerious/gram-node-frontend/commit/6a0a4bf86c8411dd5f7665c32a1703906c11f3d3).
This change also fixes the indicator for unread messages when using chat.push().
The change will be merged into master soon

**Comment by VaguelySerious** [comment]
Merged into master
