### ISSUE TITLE
 Username is in grey

### ISSUE THREAD

**Issue by simonfrey** [VaguelySerious/gram-node-frontend#4]
The username of the user sending from the website is grey on blue and not readable

**Comment by Edeltraudt** [comment]
The sending username should never be displayed or asked for, this is purely for familiarity with the replying party.

**Comment by VaguelySerious** [comment]
Addressed in [26f7ded](https://github.com/VaguelySerious/gram-node-frontend/commit/26f7ded2e20842fa0038315a3210f78f676c32de).
